type Number = float | int

WORKING_DAY_LENGTH = 3
DAY_LENGTH_HOURS = 9
TEST_DAYS = 2

LAMP_BREAK_CHANCE_MAX = 15
INITIAL_LAMP_BREAK_CHANCE_MAX = 15

RANDOM_NUTRIENT_MIN_STRENGTH_LEVEL = 15
RANDOM_NUTRIENT_MAX_STRENGTH_LEVEL = 50

RANDOM_NUTRIENT_MIN_REDUCTION_LEVEL = 0.3
RANDOM_NUTRIENT_MAX_REDUCTION_LEVEL = 5

RANDOM_NUTRIENT_MIN_REDUCTION_MULTIPLIER = 1.12
RANDOM_NUTRIENT_MAX_REDUCTION_MULTIPLIER = 2

RANDOM_LIGHT_MIN_LEVEL = 30
RANDOM_LIGHT_MAX_LEVEL = 70

START_NUTRIENT_STRENGTH = 50
START_NUTRIENT_REDUCTION_LEVEL = 1
START_NUTRIENT_REDUCTION_MULTIPLIER = 1.4
